customhost = "workdatabase-1.czw7vbg1xe2s.us-east-1.rds.amazonaws.com"
customuser = "nithin"
custompass = "sunny172002"
customdb = "student"
custombucket = "nitsamsribucket"
customregion = "us-east-1"
